-- 8º PASSO: CONFERINDO...
-- SELECT * FROM tb_perfil;

-- 7º PASSO: QUERY DE ATUALIZAÇÃO DE IDADE:
-- UPDATE tb_perfil SET idade = 20 WHERE id = 8; ~ TENTEI FAZER SET nome = Fabi WHERE turma = H, NÃO FUNCIONOU; PQ?

-- 6º PASSO: SELECT QUE RETORNE NOTA MENOR QUE 7.0:
-- SELECT * FROM tb_perfil WHERE nota < 7.0; ~ NÃO IMPLEMENTADO! ME DEI CONTA QUE ESQUECI DAS NOTAS SÓ NO FINAL DO EXERCÍCIO.

-- 5º PASSO: SELECT QUE RETORNE NOTA MAIOR QUE 7.0:
-- SELECT * FROM tb_perfil WHERE nota > 7.0; ~ NÃO IMPLEMENTADO! ME DEI CONTA QUE ESQUECI DAS NOTAS SÓ NO FINAL DO EXERCÍCIO.

-- 4º PASSO: INSERE DADOS; USEI 8X, TROCANDO OS VALUES; LEMBRAR QUE id É AUTO!
-- INSERT INTO tb_perfil (nome, turma, idade, anonascimento) VALUES ("Fabíola", "H", 19, 2003);

-- 3º PASSO: CRIA "CABEÇALHO" DA TABELA:
/*
CREATE TABLE tb_perfil (
	id INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(255) NOT NULL,
	turma CHAR(1) NOT NULL,
    idade INT NOT NULL,
    anonascimento INT NOT NULL,
    PRIMARY KEY (id)
    );
*/
-- 2º PASSO: USA BASE DE DADOS CRIADA:
-- USE db_estudantes;

-- 1º PASSO: CRIA BASE DE DADOS:
-- CREATE DATABASE db_estudantes;